export const designation = [
  { letter: "S", delay: 8 },
  { letter: "O", delay: 7 },
  { letter: "F", delay: 6 },
  { letter: "T", delay: 5 },
  { letter: "W", delay: 4 },
  { letter: "A", delay: 3 },
  { letter: "R", delay: 2 },
  { letter: "E", delay: 1 },
  { letter: " ", delay: 0 },
  { letter: "E", delay: 1 },
  { letter: "N", delay: 2 },
  { letter: "G", delay: 3 },
  { letter: "I", delay: 4 },
  { letter: "N", delay: 5 },
  { letter: "E", delay: 6 },
  { letter: "E", delay: 7 },
  { letter: "R", delay: 8 },
];
